all:
	g++ -std=c++11 -I ./ main.cpp -o main
	./main "{\"serverData\":{\"otherTTDates\":[{\"month\":\"2\",\"year\":\"2019\"},{\"month\":\"3\",\"year\":\"2019\"},{\"month\":\"4\",\"year\":\"2019\"},{\"month\":\"5\",\"year\":\"2019\"}],\"currentTTDate\":{\"month\":\"5\",\"year\":\"2019\"},\"norm\":\"160 H\"}}"