export const GET_USER_PREFERENCES_SUCCESS = 'GET_USER_PREFERENCES_SUCCESS';
export const GET_USER_PREFERENCES_PENDING = 'GET_USER_PREFERENCES_PENDING';
export const GET_USER_PREFERENCES_ERROR = 'GET_USER_PREFERENCES_ERROR';
