export const GET_USER_PREFERENCES_SUCCESS = 'GET_USER_PREFERENCES_SUCCESS';
export const GET_USER_PREFERENCES_PENDING = 'GET_USER_PREFERENCES_PENDING';
export const GET_USER_PREFERENCES_ERROR = 'GET_USER_PREFERENCES_ERROR';

export const PUT_USER_PREFERENCES_SUCCESS = 'PUT_USER_PREFERENCES_SUCCESS';
export const PUT_USER_PREFERENCES_PENDING = 'PUT_USER_PREFERENCES_PENDING';
export const PUT_USER_PREFERENCES_ERROR = 'PUT_USER_PREFERENCES_ERROR';

export const PUT_NEW_PASSWORD_SUCCESS = 'PUT_NEW_PASSWORD_SUCCESS';
export const PUT_NEW_PASSWORD_PENDING = 'PUT_NEW_PASSWORD_PENDING';
export const PUT_NEW_PASSWORD_ERROR = 'PUT_NEW_PASSWORD_ERROR';
